VAGRANTFILE_API_VERSION = "2"

$script_document_root_fix = <<-SCRIPT
mv /var/www/info.php /var/www/html/info.php
sed -i -e "s|VirtualDocumentRoot /vagrant/%0|VirtualDocumentRoot /var/www/html|g" /etc/httpd/conf.d/vhosts.conf
service httpd restart
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.pty = true
  config.vm.define "challenge" do |challenge|
    challenge.vm.box = "mcloide/centos-6.5-lamp"
    challenge.vm.network "forwarded_port", guest: 80, host: 8080
    challenge.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.provision "shell", inline: $script_document_root_fix
end
